name: bookwise_app
description: A Flutter book app UI implementation.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  provider: ^6.0.3
  http: ^1.3.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
